version: '3'
services:
  go-backend:
    build: .
    container_name: go-backend
    ports:
      - "8085:8085"
    depends_on:
      - mongodb
    environment:
      - GIN_MODE=release
      - MONGO_URI=mongodb://mongodb:27017/walletdb # MongoDB connection string
    networks:
      - app-network

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: "mongodb://mongodb:27017/walletdb"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
